package com.app.olders_rrss.Clases

import com.app.am_rrss.Clases.clsActividad

fun CrearListaActividades(): MutableList<clsActividad> {
    val listActividades: MutableList<clsActividad> = mutableListOf()

    listActividades.add(clsActividad("Act_5_RW_EscBas_GL_001", enumModulo.RW, enumCategoria.Escritura_Basica, enumPlataforma.General, "Exploración del Teclado", "Descubre el mundo del teclado paso a paso", 0.8, 1.0, 0.3, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscBas_GL_002", enumModulo.RW, enumCategoria.Escritura_Basica, enumPlataforma.General, "Configuración del Teclado", "Personaliza tu teclado para hacerlo más amigable", 0.8, 1.0, 0.3, 0.9, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscBas_GL_003", enumModulo.RW, enumCategoria.Escritura_Basica, enumPlataforma.General, "Postura de Escritura", "Encuentra la postura cómoda para escribir", 0.8, 1.0, 0.3, 0.8, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscBas_GL_004", enumModulo.RW, enumCategoria.Escritura_Basica, enumPlataforma.General, "Ejercicios de Destreza", "Mantén ágil tus dedos con ejercicios sencillos", 0.8, 1.0, 0.5, 0.7, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscBas_GL_005", enumModulo.RW, enumCategoria.Escritura_Basica, enumPlataforma.General, "Escritura de Letras", "Aprende a escribir letras con claridad y precisión", 0.8, 1.0, 0.5, 0.9, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscBas_GL_006", enumModulo.RW, enumCategoria.Escritura_Basica, enumPlataforma.General, "Escritura de Signos", "Explora la escritura de signos y símbolos", 0.8, 1.0, 0.5, 0.9, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscBas_GL_007", enumModulo.RW, enumCategoria.Escritura_Basica, enumPlataforma.General, "Escritura de Palabras", "Construye palabras para expresarte mejor", 0.8, 1.0, 0.5, 0.9, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscBas_GL_008", enumModulo.RW, enumCategoria.Escritura_Basica, enumPlataforma.General, "Oraciones Simples", "Forma oraciones sencillas y efectivas", 0.8, 1.0, 0.6, 0.9, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscBas_GL_009", enumModulo.RW, enumCategoria.Escritura_Basica, enumPlataforma.General, "Mensajes de Estado", "Comparte tu estado de ánimo de manera creativa", 0.8, 1.0, 0.7, 0.9, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_LengRRSS_GL_010", enumModulo.RW, enumCategoria.Lenguaje_RRSS, enumPlataforma.General, "Uso de Emoticones", "Expresa emociones con diversión y simpatía", 1.0, 1.0, 0.7, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_LengRRSS_GL_011", enumModulo.RW, enumCategoria.Lenguaje_RRSS, enumPlataforma.General, "Frases Impactantes", "Crea mensajes cortos que transmitan mucho", 1.0, 1.0, 0.7, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_LengRRSS_GL_012", enumModulo.RW, enumCategoria.Lenguaje_RRSS, enumPlataforma.General, "Conversación Emotiva", "Conecta emocionalmente con frases expresivas", 1.0, 1.0, 0.7, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_LengRRSS_GL_013", enumModulo.RW, enumCategoria.Lenguaje_RRSS, enumPlataforma.General, "Desafío Emotivo", "Participa en desafíos divertidos y expresivos", 1.0, 1.0, 0.7, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_LengRRSS_GL_014", enumModulo.RW, enumCategoria.Lenguaje_RRSS, enumPlataforma.General, "Comunicación Concisa", "Sé claro y directo en tus mensajes", 1.0, 1.0, 0.7, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_LengRRSS_GL_015", enumModulo.RW, enumCategoria.Lenguaje_RRSS, enumPlataforma.General, "Creación de Memes", "Diviértete creando memes y mensajes ingeniosos", 1.0, 1.0, 0.7, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_LectTipo_GL_016", enumModulo.RW, enumCategoria.Tipos_Lectura, enumPlataforma.General, "Identificación de Mensajes", "Distingue entre conversaciones privadas y públicas", 1.0, 1.0, 0.6, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_LectTipo_GL_017", enumModulo.RW, enumCategoria.Tipos_Lectura, enumPlataforma.General, "Comprensión de Publicaciones", "Lee y participa activamente en las publicaciones", 1.0, 1.0, 0.6, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_LectTipo_GL_018", enumModulo.RW, enumCategoria.Tipos_Lectura, enumPlataforma.General, "Clasificación de Mensajes", "Etiqueta correctamente tus mensajes: ¿Público o Privado?", 1.0, 1.0, 0.6, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_LectTipo_GL_019", enumModulo.RW, enumCategoria.Tipos_Lectura, enumPlataforma.General, "Desafío de Comprensión", "Participa en desafíos para mejorar la comprensión", 1.0, 1.0, 0.7, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_LectTipo_GL_020", enumModulo.RW, enumCategoria.Tipos_Lectura, enumPlataforma.General, "Interpretación de Mensajes", "Entiende el contexto de las conversaciones grupales", 1.0, 1.0, 0.7, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscMed_GL_021", enumModulo.RW, enumCategoria.Escritura_Intermedia, enumPlataforma.General, "Dictado de Palabras", "Experimenta con la escritura usando tu voz", 0.5, 0.6, 0.7, 0.7, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscMed_GL_022", enumModulo.RW, enumCategoria.Escritura_Intermedia, enumPlataforma.General, "Exploración de Teclados", "Descubre diferentes formas de escribir", 0.5, 0.6, 0.7, 0.7, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscMed_GL_023", enumModulo.RW, enumCategoria.Escritura_Intermedia, enumPlataforma.General, "Escritura con Autocorrección", "Escribe con confianza, sabiendo que puedes corregir", 0.5, 1.0, 0.7, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscMed_GL_024", enumModulo.RW, enumCategoria.Escritura_Intermedia, enumPlataforma.General, "Desafío Ortográfico", "Mejora tu ortografía con desafíos divertidos", 0.5, 1.0, 0.7, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_EscMed_GL_025", enumModulo.RW, enumCategoria.Escritura_Intermedia, enumPlataforma.General, "Práctica de Corrección", "Perfecciona tu escritura corrigiendo textos", 0.5, 1.0, 0.7, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_Accesib_GL_026", enumModulo.RW, enumCategoria.Accesibilidad_Android, enumPlataforma.General, "Exploración de Accesibilidad", "Descubre cómo hacer que tu dispositivo sea accesible", 0.3, 0.4, 0.3, 0.7, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_Accesib_GL_027", enumModulo.RW, enumCategoria.Accesibilidad_Android, enumPlataforma.General, "Adaptación Visual", "Personaliza la visualización para una mejor experiencia", 0.3, 1.0, 0.3, 0.7, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_Accesib_GL_028", enumModulo.RW, enumCategoria.Accesibilidad_Android, enumPlataforma.General, "Mejoras Auditivas", "Ajusta el sonido para una experiencia auditiva óptima", 1.0, 0.6, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_Accesib_GL_029", enumModulo.RW, enumCategoria.Accesibilidad_Android, enumPlataforma.General, "Navegación Táctil", "Domina la navegación táctil para mayor comodidad", 0.3, 1.0, 0.8, 0.7, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_Accesib_GL_030", enumModulo.RW, enumCategoria.Accesibilidad_Android, enumPlataforma.General, "Experiencia de Teclado", "Optimiza tu experiencia de escritura en el teclado", 0.3, 1.0, 0.8, 0.7, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_Accesib_GL_031", enumModulo.RW, enumCategoria.Accesibilidad_Android, enumPlataforma.General, "Configuración de Daltonismo", "Adapta los colores según tus necesidades visuales", 1.0, 1.0, 0.4, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_5_RW_Accesib_GL_032", enumModulo.RW, enumCategoria.Accesibilidad_Android, enumPlataforma.General, "Uso de Contraste", "Ajusta el contraste para facilitar la lectura", 1.0, 1.0, 0.4, 1.0, 1.0, 1.0, 1.0, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_GL_033", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.General, "Introducción a Redes Sociales", "Descubre el mundo digital: ¿Qué son las redes sociales?", 1.0, 1.0, 1.0, 1.0, 0.2, 1.0, 0.8, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_GL_034", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.General, "Funciones de Redes Sociales", "Explorando el universo online: ¿Para qué sirven las redes sociales?", 1.0, 1.0, 1.0, 1.0, 0.2, 1.0, 0.8, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_GL_035", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.General, "Redes Sociales Populares", "Conoce las favoritas: ¿Cuáles son las redes sociales más usadas?", 1.0, 1.0, 1.0, 1.0, 0.3, 1.0, 0.8, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_FB_036", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.Facebook, "Facebook: Bienvenida", "¡Bienvenido a Facebook! Creando tu espacio digital.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_YT_037", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.Youtube, "Youtube: Exploración", "Descubre Youtube: Tu ventana a un mundo de videos.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.8, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_WA_038", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.Whatsapp, "Whatsapp: Inicio", "Comunicación fácil: Descubre Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_IG_039", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.Instagram, "Instagram: Exploración", "Explora Instagram: Captura y comparte momentos especiales.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.8, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_TT_040", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.TikTok, "TikTok: Diversión Instantánea", "¡Diviértete en segundos! Descubre TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.8, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_TW_041", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.X_Twitter, "Twitter: Inicio", "¡Sigue el trino! Descubre el mundo de Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.8, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_PT_042", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.Pinterest, "Pinterest: Inspiración", "Inspírate y crea con Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.8, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_FB_M_043", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.Fb_Messenger, "Messenger: Mensajería", "Mensajería simple: Facebook Messenger al alcance.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.8, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_IntroRS_LI_044", enumModulo.RRSS, enumCategoria.Intro_RRSS, enumPlataforma.LinkedIn, "LinkedIn: Exploración", "Profesional y conectado: Explorando LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_GL_045", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.General, "Interacción Básica", "Navegando con confianza: Aspectos básicos de la interacción.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_GL_046", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.General, "Instalación de Aplicaciones", "¡Hazlo fácil! Instalando aplicaciones en tu dispositivo.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_GL_047", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.General, "Creación de Correo", "Tu puerta al mundo digital: Creando tu correo electrónico.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_GL_048", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.General, "Apertura de Aplicación", "Un toque para empezar: Abriendo aplicaciones con facilidad.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_GL_049", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.General, "Uso de Lupa", "¡Más grande y claro! Explorando con la lupa de Android.", 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_GL_050", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.General, "Práctica Táctil", "Toque amigable: Practicando con la pantalla táctil.", 1.0, 1.0, 1.0, 0.7, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_FB_051", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Facebook, "Inicio de Sesión", "Conéctate fácilmente: Iniciando sesión en Facebook.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_FB_052", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Facebook, "Exploración de Noticias", "¡Al día! Explorando las noticias y actualizaciones.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_FB_053", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Facebook, "Exploración de Álbumes", "Viaje visual: Explorando álbumes de amigos y familiares.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_YT_054", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Youtube, "Inicio de Sesión con Google", "Mundo de videos: Iniciando sesión en Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_YT_055", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Youtube, "Visualización de Videos", "¡Recomendaciones a la vista! Explorando videos en Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_YT_056", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Youtube, "Exploración de Canales", "Canales favoritos: Explorando suscripciones en Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_WA_057", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Whatsapp, "Inicio de Sesión con Número", "Sencillo y seguro: Iniciando sesión en Whatsapp con tu número.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_WA_058", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Whatsapp, "Lectura de Mensajes", "¡Mensajes al instante! Explorando mensajes y estados en Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_WA_059", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Whatsapp, "Lectura en Grupos", "Comunidad virtual: Leyendo mensajes en grupos de Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_IG_060", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Instagram, "Inicio de Sesión", "Captura momentos: Iniciando sesión en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_IG_061", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Instagram, "Exploración de Publicaciones", "Belleza visual: Explorando publicaciones en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_IG_062", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Instagram, "Exploración de Historias", "Historias efímeras: Explorando historias en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_IG_063", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Instagram, "Navegación de Perfiles", "Arte y cultura: Navegando perfiles en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_TT_064", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.TikTok, "Inicio de Sesión", "¡Diviértete al instante! Iniciando sesión en TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_TT_065", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.TikTok, "Navegación de Videos", "Brevedad creativa: Navegando videos cortos en TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_TT_066", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.TikTok, "Contenido Personalizado", "¡Para ti! Descubriendo contenido personalizado en TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_TT_067", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.TikTok, "Exploración de Desafíos", "Únete a la tendencia: Explorando desafíos en TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_TW_068", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.X_Twitter, "Inicio de Sesión", "¡Tweets al alcance! Iniciando sesión en Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.6, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_TW_069", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.X_Twitter, "Lectura de Tweets", "Al día: Leyendo tweets y tendencias en Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.6, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_TW_070", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.X_Twitter, "Revisión de Línea de Tiempo", "¡Reciente y relevante! Revisando la línea de tiempo en Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.6, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_TW_071", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.X_Twitter, "Exploración de Perfiles", "Conexiones interesantes: Explorando perfiles en Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.6, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_PT_072", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Pinterest, "Inicio de Sesión con Google/Facebook", "Inspiración visual: Iniciando sesión en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.6, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_PT_073", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Pinterest, "Descubrimiento de Pines", "¡Inspírate! Descubriendo pines e inspiración en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.6, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_PT_074", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Pinterest, "Navegación de Tableros", "Viaje temático: Navegando por tableros en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.6, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_FB_M_075", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Fb_Messenger, "Inicio de Sesión con Facebook", "Comunicación directa: Iniciando sesión en Facebook Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_FB_M_076", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Fb_Messenger, "Lectura de Conversaciones", "Conversaciones fluidas: Leyendo mensajes y medios compartidos en Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_FB_M_077", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.Fb_Messenger, "Lectura de Mensajes Antiguos", "¡Recuerdos digitales! Leyendo mensajes antiguos en Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.6, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_LI_078", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.LinkedIn, "Inicio de Sesión", "Conexiones profesionales: Iniciando sesión en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_LI_079", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.LinkedIn, "Exploración de Contenido Profesional", "Carrera digital: Explorando contenido profesional en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_InteracPas_LI_080", enumModulo.RRSS, enumCategoria.Interacc_Pasiva, enumPlataforma.LinkedIn, "Navegación en el Feed", "Actualizaciones de carrera: Navegando por publicaciones en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_Config_GL_081", enumModulo.RRSS, enumCategoria.Configuracion, enumPlataforma.General, "Introducción a la Configuración", "Control total: Descubriendo qué es la configuración.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_Config_GL_082", enumModulo.RRSS, enumCategoria.Configuracion, enumPlataforma.General, "Funciones de Configuración", "A tu medida: Explorando por qué configuramos.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_Config_FB_083", enumModulo.RRSS, enumCategoria.Configuracion, enumPlataforma.Facebook, "Personalización de Notificaciones", "¡A tu manera! Personalizando notificaciones y preferencias en Facebook.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_Config_YT_084", enumModulo.RRSS, enumCategoria.Configuracion, enumPlataforma.Youtube, "Personalización de Configuraciones", "Videos a medida: Personalizando configuraciones en Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.5, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_Config_WA_085", enumModulo.RRSS, enumCategoria.Configuracion, enumPlataforma.Whatsapp, "Personalización de Preferencias", "¡Privacidad y personalización! Configurando Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_Config_IG_086", enumModulo.RRSS, enumCategoria.Configuracion, enumPlataforma.Instagram, "Configuración de Notificaciones", "Estilo propio: Configurando notificaciones y preferencias en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.5, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_Config_TT_087", enumModulo.RRSS, enumCategoria.Configuracion, enumPlataforma.TikTok, "Configuración de Notificaciones", "¡Ajustes divertidos! Personalizando notificaciones", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.5, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_Config_TW_088", enumModulo.RRSS, enumCategoria.Configuracion, enumPlataforma.X_Twitter, "Configuración de Notificaciones", "Tweets a medida: Configurando notificaciones en Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.5, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_Config_PT_089", enumModulo.RRSS, enumCategoria.Configuracion, enumPlataforma.Pinterest, "Configuración de Notificaciones", "Inspiración a tu manera: Configurando notificaciones en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.5, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_Config_FB_M_090", enumModulo.RRSS, enumCategoria.Configuracion, enumPlataforma.Fb_Messenger, "Personalización de Notificaciones en Messenger", "Comunicación personalizada: Configurando notificaciones en Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.5, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_Config_LI_091", enumModulo.RRSS, enumCategoria.Configuracion, enumPlataforma.LinkedIn, "Configuración de Notificaciones", "Red profesional: Configurando notificaciones en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_FB_092", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Facebook, "Comentario en Publicaciones", "¡Comparte tu opinión! Comentando en publicaciones de Facebook.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_FB_093", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Facebook, "Mensajes Privados", "¡Conéctate más! Enviando mensajes privados en Facebook.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_FB_094", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Facebook, "Agregar Amigos", "¡Haz nuevos lazos! Agregando amigos en Facebook.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_YT_095", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Youtube, "Comentario en Videos", "¡Opina sobre videos! Comentando en videos de Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_YT_096", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Youtube, "Comentarios en Youtube", "¡Conecta con creadores! Enviando comentarios en Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_YT_097", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Youtube, "Suscripción a Canales", "¡Sigue tu pasión! Suscribiéndote a canales en Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_WA_098", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Whatsapp, "Comentario en Estados", "¡Comparte tu día! Comentando estados en Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_WA_099", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Whatsapp, "Mensajes en Whatsapp", "¡Conversación fluida! Enviando y respondiendo mensajes en Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_WA_100", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Whatsapp, "Agregar Contactos", "¡Expandiendo contactos! Agregando nuevos amigos en Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_IG_101", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Instagram, "Comentario en Fotos", "¡Expresa tu admiración! Comentando en fotos y videos de Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_IG_102", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Instagram, "Mensajes Directos", "¡Conexiones personales! Enviando mensajes directos en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_IG_103", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Instagram, "Seguir Perfiles", "¡Descubre nuevos horizontes! Siguiendo nuevos perfiles en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_TT_104", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.TikTok, "Comentario en Videos Cortos", "¡Diviértete y comenta! Comentando en videos cortos de TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_TT_105", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.TikTok, "Mensajes en TikTok", "¡Conecta con creatividad! Enviando mensajes en TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_TT_106", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.TikTok, "Seguir Creadores", "¡Sigue la magia! Siguiendo a creadores de contenido en TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_TW_107", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.X_Twitter, "Comentario en Tweets", "¡Participa en la conversación! Comentando en tweets de Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.4, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_TW_108", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.X_Twitter, "Mensajes Directos en Twitter", "¡Comunícate directamente! Enviando mensajes directos en Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.4, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_TW_109", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.X_Twitter, "Seguir Usuarios", "¡Expande tu red! Siguiendo a nuevos usuarios en Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.4, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_PT_110", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Pinterest, "Comentario en Pines", "¡Expresa tu inspiración! Comentando en pines de Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.4, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_PT_111", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Pinterest, "Mensajes en Pinterest", "¡Conecta a través de ideas! Enviando mensajes en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.4, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_PT_112", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Pinterest, "Seguir Tableros", "¡Descubre nuevos mundos! Siguiendo nuevos tableros y usuarios en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.4, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_FB_M_113", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Fb_Messenger, "Comentario en Conversaciones", "¡Comparte tu experiencia! Comentando en conversaciones de Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_FB_M_114", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Fb_Messenger, "Mensajes a Amigos", "¡Comunicación directa! Enviando mensajes a amigos y grupos en Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_FB_M_115", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.Fb_Messenger, "Agregar Contactos en Messenger", "¡Amplía tu círculo! Agregando nuevos contactos en Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.4, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_LI_116", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.LinkedIn, "Comentario en Publicaciones y Artículos", "¡Participa en lo profesional! Comentando en publicaciones y artículos de LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_LI_117", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.LinkedIn, "Mensajes a Conexiones", "¡Conéctate profesionalmente! Enviando mensajes en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_InteracBas_LI_118", enumModulo.RRSS, enumCategoria.Interacc_Basica, enumPlataforma.LinkedIn, "Conectar Profesionales", "¡Expande tu red laboral! Conectando con nuevos profesionales en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_FB_119", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Facebook, "Publicar Estado", "¡Comparte tu día! Publicando estados con texto e imágenes en Facebook.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_FB_120", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Facebook, "Compartir Álbumes", "¡Recuerdos digitales! Compartiendo álbumes de fotos y videos en Facebook.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_FB_121", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Facebook, "Crear Historias", "¡Historias visuales! Utilizando la cámara para crear historias en Facebook.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_YT_122", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Youtube, "Subir Videos", "¡Crea y comparte! Subiendo videos a la plataforma de Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_YT_123", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Youtube, "Crear Listas de Reproducción", "¡Playlist personalizada! Creando y compartiendo listas de reproducción en Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_YT_124", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Youtube, "Crear Contenido Multimedia", "¡Cámara en acción! Utilizando la cámara para crear contenido multimedia en Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_WA_125", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Whatsapp, "Publicar Estados en Whatsapp", "¡Exprésate en Whatsapp! Publicando estados con texto, fotos y videos.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_WA_126", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Whatsapp, "Compartir Contenido en Chats", "¡Conexión multimedia! Compartiendo contenido multimedia en chats de Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_WA_127", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Whatsapp, "Tomar y Compartir Fotos/Videos", "¡Captura y comparte! Tomando y compartiendo fotos y videos desde la aplicación de Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_IG_128", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Instagram, "Publicar en el Feed", "¡Tu galería digital! Publicando fotos y videos en el feed de Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_IG_129", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Instagram, "Compartir Historias", "¡Historias que desaparecen! Compartiendo historias con contenido efímero en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_IG_130", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Instagram, "Crear Contenido Visual", "¡Crea visualmente! Utilizando la cámara para crear contenido visual en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_TT_131", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.TikTok, "Crear Videos Cortos", "¡Diviértete creando! Creando y publicando videos cortos en TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_TT_132", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.TikTok, "Grabar Contenido Divertido", "¡Diversión en cada grabación! Utilizando la cámara para grabar contenido divertido en TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_TT_133", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.TikTok, "Compartir Videos Editados", "¡Añade magia a tus videos! Compartiendo videos con efectos y ediciones en TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_TW_134", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.X_Twitter, "Twittear con Multimedia", "¡Exprésate en 280 caracteres! Twitteando con texto y multimedia en Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.3, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_TW_135", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.X_Twitter, "Compartir en Tweets", "¡Visualiza tu mundo! Compartiendo fotos y videos en tweets de Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.3, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_TW_136", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.X_Twitter, "Capturar Momentos", "¡Captura momentos únicos! Utilizando la cámara para capturar momentos en Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.3, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_PT_137", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Pinterest, "Pinear e Inspirar", "¡Inspira y comparte! Pineando y compartiendo imágenes inspiradoras en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.3, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_PT_138", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Pinterest, "Crear Tableros Temáticos", "¡Organiza tu inspiración! Creando tableros temáticos y publicando contenido en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.3, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_PT_139", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Pinterest, "Capturar Ideas Visuales", "¡Captura tu creatividad! Utilizando la cámara para capturar ideas visuales en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.3, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_FB_M_140", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Fb_Messenger, "Compartir Multimedia en Conversaciones", "¡Conexión multimedia! Compartiendo fotos y videos en conversaciones de Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_FB_M_141", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Fb_Messenger, "Publicar Actualizaciones", "¡Actualízate en Messenger! Publicando actualizaciones de estado en Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_FB_M_142", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.Fb_Messenger, "Enviar Multimedia", "¡Envía momentos visuales! Utilizando la cámara para enviar fotos y videos en Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_LI_143", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.LinkedIn, "Publicar Contenido", "¡Profesional y actualizado! Publicando actualizaciones de estado y contenido en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_LI_144", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.LinkedIn, "Compartir Artículos", "¡Comparte tu conocimiento! Compartiendo artículos y publicaciones en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_InteracMed_LI_145", enumModulo.RRSS, enumCategoria.Interacci_Intermedia, enumPlataforma.LinkedIn, "Crear Contenido Profesional", "¡Visualiza tu trayectoria! Utilizando la cámara para crear contenido de carrera en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_FB_146", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Facebook, "Configurar Privacidad", "¡Tu espacio seguro! Revisando y ajustando la configuración de privacidad en Facebook.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_FB_147", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Facebook, "Proteger Identidad", "¡Protege tu identidad! Evitando compartir información personal sensible en el perfil de Facebook.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_FB_148", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Facebook, "Ignorar Solicitudes", "¡Círculo confiable! Ignorando solicitudes de amistad de desconocidos en Facebook.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_YT_149", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Youtube, "Configurar Privacidad en Youtube", "¡Tu canal, tus reglas! Configurando la privacidad del canal en Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_YT_150", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Youtube, "Ser cuidadoso al Comentar", "¡Comenta con cuidado! Siendo cuidadoso al compartir comentarios o información personal en Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_YT_151", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Youtube, "Desactivar Comentarios", "¡Controla tu espacio! Desactivando comentarios en videos si así lo prefieres en Youtube.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.7, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_WA_152", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Whatsapp, "Configurar Privacidad en Whatsapp", "¡Tu privacidad, tus reglas! Configurando opciones de privacidad en Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_WA_153", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Whatsapp, "Evitar Enlaces Peligrosos", "¡Cuida tu seguridad! Evitando abrir enlaces o descargar archivos de desconocidos en Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_WA_154", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Whatsapp, "Proteger Datos Personales", "¡Protege tus datos! Evitando compartir información financiera o personal por mensajes en Whatsapp.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_IG_155", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Instagram, "Ajustar Privacidad en Instagram", "¡Contenido controlado! Ajustando la configuración de privacidad en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_IG_156", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Instagram, "Eliminar Seguidores", "¡Círculo confiable! Revisando y eliminando seguidores no deseados en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_IG_157", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Instagram, "Proteger Cuenta", "¡Cuenta segura! Utilizando una contraseña fuerte para proteger la cuenta en Instagram.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.6, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_TT_158", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.TikTok, "Configurar Privacidad en TikTok", "¡Tu espacio, tus reglas! Configurando la privacidad de la cuenta en TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_TT_159", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.TikTok, "Ser cuidadoso al Compartir en TikTok", "¡Cautela creativa! Siendo cuidadoso al compartir detalles personales en videos de TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_TT_160", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.TikTok, "Eliminar Comentarios", "¡Comentarios seguros! Revisando y eliminando comentarios no deseados en publicaciones de TikTok.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_TW_161", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.X_Twitter, "Ajustar Privacidad en Twitter", "¡Tu espacio, tus reglas! Ajustando la configuración de privacidad en Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.3, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_TW_162", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.X_Twitter, "Proteger Ubicación", "¡Protege tu ubicación! Evitando compartir información de ubicación en tweets de Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.3, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_TW_163", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.X_Twitter, "Identificar enlaces desconocidos", "¡Navega seguro! Evitando hacer clic en enlaces de origen desconocido en Twitter.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.4, 0.3, 0.5))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_PT_164", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Pinterest, "Configurar privacidad", "¡Inspira con seguridad! Revisando la configuración de privacidad en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.3, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_PT_165", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Pinterest, "Tableros privados", "¡Privacidad creativa! Manteniendo tableros privados para contenido sensible en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.3, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_PT_166", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Pinterest, "Cuidado al compartir enlaces", "¡Cautela visual! Siendo cuidadoso al pinear contenido con enlaces externos en Pinterest.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.3, 0.7))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_FB_M_167", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Fb_Messenger, "Bloqueo y reporte de contactos", "¡Contactos bajo control! Utilizando opciones de bloqueo y reporte en Facebook Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_FB_M_168", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Fb_Messenger, "Cuidado al compartir datos privados", "¡Protege tu información! Evitando compartir detalles personales o financieros por mensajes en Facebook Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_FB_M_169", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.Fb_Messenger, "Cuidado al abrir enlaces", "¡Conversaciones seguras! No abriendo enlaces de desconocidos en conversaciones de Messenger.", 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.3, 1.0))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_LI_170", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.LinkedIn, "Configurar privacidad", "¡Profesional y seguro! Revisando la configuración de privacidad en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_LI_171", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.LinkedIn, "Conectar a contactos confiables", "¡Conexiones confiables! Conectando solo con personas conocidas y confiables en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 0.8))
    listActividades.add(clsActividad("Act_6_RRSS_SegPriv_LI_172", enumModulo.RRSS, enumCategoria.Seguridad_Privacidad, enumPlataforma.LinkedIn, "Cuidado al compartir datos en perfil", "¡Perfil profesional seguro! No compartiendo información sensible en la descripción del perfil en LinkedIn.", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.3, 0.8))

    return listActividades
}

/*
Codigo	Modulo	Categoría	Plataforma	Denominacion	Texto_Usuario	Eval_1	Eval_2	Eval_3	Eval_4	Eval_5	Opc_1	Opc_2	Opc_3
Act_5_RW_EscBas_GL_001	RW	Escritura básica	General	Como entender el teclado	Descubre el mundo del teclado paso a paso	0,8	1	0,3	1	1	1	1	1
Act_5_RW_EscBas_GL_002	RW	Escritura básica	General	Configuración básica del teclado	Personaliza tu teclado para hacerlo más amigable	0,8	1	0,3	0,9	1	1	1	1
Act_5_RW_EscBas_GL_003	RW	Escritura básica	General	Posicionamiento de Dedos	Encuentra la postura cómoda para escribir	0,8	1	0,3	0,8	1	1	1	1
Act_5_RW_EscBas_GL_004	RW	Escritura básica	General	Ejercicios de Dedos y Teclas	Mantén ágil tus dedos con ejercicios sencillos	0,8	1	0,5	0,7	1	1	1	1
Act_5_RW_EscBas_GL_005	RW	Escritura básica	General	Escritura de Letras (mayúsculas y minúsculas)	Aprende a escribir letras con claridad y precisión	0,8	1	0,5	0,9	1	1	1	1
Act_5_RW_EscBas_GL_006	RW	Escritura básica	General	Escritura de signos	Explora la escritura de signos y símbolos	0,8	1	0,5	0,9	1	1	1	1
Act_5_RW_EscBas_GL_007	RW	Escritura básica	General	Escritura de Palabras	Construye palabras para expresarte mejor	0,8	1	0,5	0,9	1	1	1	1
Act_5_RW_EscBas_GL_008	RW	Escritura básica	General	Oraciones Simples	Forma oraciones sencillas y efectivas	0,8	1	0,6	0,9	1	1	1	1
Act_5_RW_EscBas_GL_009	RW	Escritura básica	General	Mensajes de Estado	Comparte tu estado de ánimo de manera creativa	0,8	1	0,7	0,9	1	1	1	1
Act_5_RW_LengRRSS_GL_010	RW	Lenguaje en RRSS	General	Uso Creativo de Emoticones y Emojis	Expresa emociones con diversión y simpatía	1	1	0,7	1	1	1	1	1
Act_5_RW_LengRRSS_GL_011	RW	Lenguaje en RRSS	General	Construcción de Frases Breves y Impactantes	Crea mensajes cortos que transmitan mucho	1	1	0,7	1	1	1	1	1
Act_5_RW_LengRRSS_GL_012	RW	Lenguaje en RRSS	General	Conversación Emotiva con Frases Cortas	Conecta emocionalmente con frases expresivas	1	1	0,7	1	1	1	1	1
Act_5_RW_LengRRSS_GL_013	RW	Lenguaje en RRSS	General	Desafío: Expresa Emociones con Emoticones	Participa en desafíos divertidos y expresivos	1	1	0,7	1	1	1	1	1
Act_5_RW_LengRRSS_GL_014	RW	Lenguaje en RRSS	General	Comunicación Efectiva con Frases Concisas	Sé claro y directo en tus mensajes	1	1	0,7	1	1	1	1	1
Act_5_RW_LengRRSS_GL_015	RW	Lenguaje en RRSS	General	Creación de Frases Breves y Memes Divertidos	Diviértete creando memes y mensajes ingeniosos	1	1	0,7	1	1	1	1	1
Act_5_RW_LectTipo_GL_016	RW	Tipos de lectura	General	Identificación de Mensajes Públicos y Privados	Distingue entre conversaciones privadas y públicas	1	1	0,6	1	1	1	1	1
Act_5_RW_LectTipo_GL_017	RW	Tipos de lectura	General	Comprensión de Publicaciones: Leer y Responder	Lee y participa activamente en las publicaciones	1	1	0,6	1	1	1	1	1
Act_5_RW_LectTipo_GL_018	RW	Tipos de lectura	General	Clasificación: ¿Público o Privado?	Etiqueta correctamente tus mensajes: ¿Público o Privado?	1	1	0,6	1	1	1	1	1
Act_5_RW_LectTipo_GL_019	RW	Tipos de lectura	General	Desafío de Comprensión: Responde Preguntas sobre Publicaciones	Participa en desafíos para mejorar la comprensión	1	1	0,7	1	1	1	1	1
Act_5_RW_LectTipo_GL_020	RW	Tipos de lectura	General	Interpretación: Comprender el Contexto de Mensajes en Grupo	Entiende el contexto de las conversaciones grupales	1	1	0,7	1	1	1	1	1
Act_5_RW_EscMed_GL_021	RW	Escritura intermedia	General	Dictado de Palabras: Practicando la Escritura por Voz	Experimenta con la escritura usando tu voz	0,5	0,6	0,7	0,7	1	1	1	1
Act_5_RW_EscMed_GL_022	RW	Escritura intermedia	General	Exploración de Alternativas de Teclado	Descubre diferentes formas de escribir	0,5	0,6	0,7	0,7	1	1	1	1
Act_5_RW_EscMed_GL_023	RW	Escritura intermedia	General	Escritura Creativa con Autocorrección	Escribe con confianza, sabiendo que puedes corregir	0,5	1	0,7	1	1	1	1	1
Act_5_RW_EscMed_GL_024	RW	Escritura intermedia	General	Desafío Ortográfico: Corrige Errores de Texto	Mejora tu ortografía con desafíos divertidos	0,5	1	0,7	1	1	1	1	1
Act_5_RW_EscMed_GL_025	RW	Escritura intermedia	General	Práctica de Corrección: Mejorando la Redacción Interactiva	Perfecciona tu escritura corrigiendo textos	0,5	1	0,7	1	1	1	1	1
Act_5_RW_Accesib_GL_026	RW	Accesibilidad de Android	General	Exploración de Funciones de Accesibilidad en Android	Descubre cómo hacer que tu dispositivo sea accesible	0,3	0,4	0,3	0,7	1	1	1	1
Act_5_RW_Accesib_GL_027	RW	Accesibilidad de Android	General	Adaptación Visual: Ajustes para Mejorar la Visión	Personaliza la visualización para una mejor experiencia	0,3	1	0,3	0,7	1	1	1	1
Act_5_RW_Accesib_GL_028	RW	Accesibilidad de Android	General	Mejoras para la audición	Ajusta el sonido para una experiencia auditiva óptima	1	0,6	1	1	1	1	1	1
Act_5_RW_Accesib_GL_029	RW	Accesibilidad de Android	General	Navegación Táctil: Uso Eficiente en Dispositivos Táctiles	Domina la navegación táctil para mayor comodidad	0,3	1	0,8	0,7	1	1	1	1
Act_5_RW_Accesib_GL_030	RW	Accesibilidad de Android	General	Experiencia de Teclado: Personalización y Mejoras Táctiles	Optimiza tu experiencia de escritura en el teclado	0,3	1	0,8	0,7	1	1	1	1
Act_5_RW_Accesib_GL_031	RW	Accesibilidad de Android	General	Configuración para Daltonismo	Adapta los colores según tus necesidades visuales	1	1	0,4	1	1	1	1	1
Act_5_RW_Accesib_GL_032	RW	Accesibilidad de Android	General	Uso de Opciones de Contraste	Ajusta el contraste para facilitar la lectura	1	1	0,4	1	1	1	1	1
Act_6_RRSS_IntroRS_GL_033	RRSS	Introducción a las Redes Sociales	General	¿Qué son las redes sociales?	Descubre el mundo digital: ¿Qué son las redes sociales?	1	1	1	1	0,2	1	0,8	1
Act_6_RRSS_IntroRS_GL_034	RRSS	Introducción a las Redes Sociales	General	¿Para qué sirven?	Explorando el universo online: ¿Para qué sirven las redes sociales?	1	1	1	1	0,2	1	0,8	1
Act_6_RRSS_IntroRS_GL_035	RRSS	Introducción a las Redes Sociales	General	Redes sociales más usadas	Conoce las favoritas: ¿Cuáles son las redes sociales más usadas?	1	1	1	1	0,3	1	0,8	1
Act_6_RRSS_IntroRS_FB_036	RRSS	Introducción a las Redes Sociales	Facebook	Facebook	¡Bienvenido a Facebook! Creando tu espacio digital.	1	1	1	1	1	1	0,8	1
Act_6_RRSS_IntroRS_YT_037	RRSS	Introducción a las Redes Sociales	Youtube	Youtube	Descubre Youtube: Tu ventana a un mundo de videos.	1	1	1	1	1	0,7	0,8	1
Act_6_RRSS_IntroRS_WA_038	RRSS	Introducción a las Redes Sociales	Whatsapp	Whatsapp	Comunicación fácil: Descubre Whatsapp.	1	1	1	1	1	1	0,8	1
Act_6_RRSS_IntroRS_IG_039	RRSS	Introducción a las Redes Sociales	Instagram	Instagram	Explora Instagram: Captura y comparte momentos especiales.	1	1	1	1	1	0,6	0,8	1
Act_6_RRSS_IntroRS_TT_040	RRSS	Introducción a las Redes Sociales	TikTok	TikTok	¡Diviértete en segundos! Descubre TikTok.	1	1	1	1	1	0,8	0,8	1
Act_6_RRSS_IntroRS_TW_041	RRSS	Introducción a las Redes Sociales	X (Twitter)	X (Twitter)	¡Sigue el trino! Descubre el mundo de Twitter.	1	1	1	1	1	0,4	0,8	0,5
Act_6_RRSS_IntroRS_PT_042	RRSS	Introducción a las Redes Sociales	Pinterest	Pinterest	Inspírate y crea con Pinterest.	1	1	1	1	1	0,2	0,8	7
Act_6_RRSS_IntroRS_FB_M_043	RRSS	Introducción a las Redes Sociales	Facebook Messenger	Facebook Messenger	Mensajería simple: Facebook Messenger al alcance.	1	1	1	1	1	0,8	0,8	1
Act_6_RRSS_IntroRS_LI_044	RRSS	Introducción a las Redes Sociales	LinkedIn	LinkedIn	Profesional y conectado: Explorando LinkedIn.	1	1	1	1	1	1	0,8	0,8
Act_6_RRSS_InteracPas_GL_045	RRSS	Interacción Pasiva	General	Aspectos básicos	Navegando con confianza: Aspectos básicos de la interacción.	1	1	1	1	1	1	0,6	1
Act_6_RRSS_InteracPas_GL_046	RRSS	Interacción Pasiva	General	Instalar una aplicación	¡Hazlo fácil! Instalando aplicaciones en tu dispositivo.	1	1	1	1	1	1	0,6	1
Act_6_RRSS_InteracPas_GL_047	RRSS	Interacción Pasiva	General	Crear un correo	Tu puerta al mundo digital: Creando tu correo electrónico.	1	1	1	1	1	1	0,6	1
Act_6_RRSS_InteracPas_GL_048	RRSS	Interacción Pasiva	General	Abrir una aplicación	Un toque para empezar: Abriendo aplicaciones con facilidad.	1	1	1	1	1	1	0,6	1
Act_6_RRSS_InteracPas_GL_049	RRSS	Interacción Pasiva	General	Usar lupa de Android	¡Más grande y claro! Explorando con la lupa de Android.	0,5	1	1	1	1	1	0,6	1
Act_6_RRSS_InteracPas_GL_050	RRSS	Interacción Pasiva	General	Practicar con touch screen	Toque amigable: Practicando con la pantalla táctil.	1	1	1	0,7	1	1	0,6	1
Act_6_RRSS_InteracPas_FB_051	RRSS	Interacción Pasiva	Facebook	Iniciar sesión o registrarse	Conéctate fácilmente: Iniciando sesión en Facebook.	1	1	1	1	1	1	0,6	1
Act_6_RRSS_InteracPas_FB_052	RRSS	Interacción Pasiva	Facebook	Explorar Noticias y Actualizaciones	¡Al día! Explorando las noticias y actualizaciones.	1	1	1	1	1	1	0,6	1
Act_6_RRSS_InteracPas_FB_053	RRSS	Interacción Pasiva	Facebook	Explorar Álbumes de Fotos de Amigos y Familiares	Viaje visual: Explorando álbumes de amigos y familiares.	1	1	1	1	1	1	0,6	1
Act_6_RRSS_InteracPas_YT_054	RRSS	Interacción Pasiva	Youtube	Iniciar sesión o registrarse con tu cuenta de Google.	Mundo de videos: Iniciando sesión en Youtube.	1	1	1	1	1	0,7	0,6	1
Act_6_RRSS_InteracPas_YT_055	RRSS	Interacción Pasiva	Youtube	Visualización de Videos Recomendados	¡Recomendaciones a la vista! Explorando videos en Youtube.	1	1	1	1	1	0,7	0,6	1
Act_6_RRSS_InteracPas_YT_056	RRSS	Interacción Pasiva	Youtube	Explorar Canales de Suscripciones	Canales favoritos: Explorando suscripciones en Youtube.	1	1	1	1	1	0,7	0,6	1
Act_6_RRSS_InteracPas_WA_057	RRSS	Interacción Pasiva	Whatsapp	Utilizar tu número de teléfono para iniciar sesión o registrarte.	Sencillo y seguro: Iniciando sesión en Whatsapp con tu número.	1	1	1	1	1	1	0,6	1
Act_6_RRSS_InteracPas_WA_058	RRSS	Interacción Pasiva	Whatsapp	Lectura de Mensajes y Estados	¡Mensajes al instante! Explorando mensajes y estados en Whatsapp.	1	1	1	1	1	1	0,6	1
Act_6_RRSS_InteracPas_WA_059	RRSS	Interacción Pasiva	Whatsapp	Leer Mensajes en Grupos	Comunidad virtual: Leyendo mensajes en grupos de Whatsapp.	1	1	1	1	1	1	0,6	1
Act_6_RRSS_InteracPas_IG_060	RRSS	Interacción Pasiva	Instagram	Iniciar sesión o registrarse	Captura momentos: Iniciando sesión en Instagram.	1	1	1	1	1	0,6	0,6	1
Act_6_RRSS_InteracPas_IG_061	RRSS	Interacción Pasiva	Instagram	Exploración de Publicaciones Visuales	Belleza visual: Explorando publicaciones en Instagram.	1	1	1	1	1	0,6	0,6	1
Act_6_RRSS_InteracPas_IG_062	RRSS	Interacción Pasiva	Instagram	Explorar Historias de Amigos y Páginas Seguidas	Historias efímeras: Explorando historias en Instagram.	1	1	1	1	1	0,6	0,6	1
Act_6_RRSS_InteracPas_IG_063	RRSS	Interacción Pasiva	Instagram	Navegar por Perfiles de Artistas y Figuras de Interés	Arte y cultura: Navegando perfiles en Instagram.	1	1	1	1	1	0,6	0,6	1
Act_6_RRSS_InteracPas_TT_064	RRSS	Interacción Pasiva	TikTok	Iniciar sesión o registrarse	¡Diviértete al instante! Iniciando sesión en TikTok.	1	1	1	1	1	0,8	0,6	1
Act_6_RRSS_InteracPas_TT_065	RRSS	Interacción Pasiva	TikTok	Navegación por Videos Cortos	Brevedad creativa: Navegando videos cortos en TikTok.	1	1	1	1	1	0,8	0,6	1
Act_6_RRSS_InteracPas_TT_066	RRSS	Interacción Pasiva	TikTok	Visualizar la Página "Para Ti" con Contenido Personalizado	¡Para ti! Descubriendo contenido personalizado en TikTok.	1	1	1	1	1	0,8	0,6	1
Act_6_RRSS_InteracPas_TT_067	RRSS	Interacción Pasiva	TikTok	Explorar Desafíos y Tendencias Populares	Únete a la tendencia: Explorando desafíos en TikTok.	1	1	1	1	1	0,8	0,6	1
Act_6_RRSS_InteracPas_TW_068	RRSS	Interacción Pasiva	X (Twitter)	Iniciar sesión o registrarse	¡Tweets al alcance! Iniciando sesión en Twitter.	1	1	1	1	1	0,4	0,6	0,5
Act_6_RRSS_InteracPas_TW_069	RRSS	Interacción Pasiva	X (Twitter)	Lectura de Tweets y Tendencias	Al día: Leyendo tweets y tendencias en Twitter.	1	1	1	1	1	0,4	0,6	0,5
Act_6_RRSS_InteracPas_TW_070	RRSS	Interacción Pasiva	X (Twitter)	Revisar la Línea de Tiempo para Tweets Recientes	¡Reciente y relevante! Revisando la línea de tiempo en Twitter.	1	1	1	1	1	0,4	0,6	0,5
Act_6_RRSS_InteracPas_TW_071	RRSS	Interacción Pasiva	X (Twitter)	Explorar Perfiles de Usuarios Relevantes	Conexiones interesantes: Explorando perfiles en Twitter.	1	1	1	1	1	0,4	0,6	0,5
Act_6_RRSS_InteracPas_PT_072	RRSS	Interacción Pasiva	Pinterest	Iniciar sesión o registrarse con tu cuenta de Google o Facebook.	Inspiración visual: Iniciando sesión en Pinterest.	1	1	1	1	1	0,2	0,6	7
Act_6_RRSS_InteracPas_PT_073	RRSS	Interacción Pasiva	Pinterest	Descubrimiento de Pines e Inspiración	¡Inspírate! Descubriendo pines e inspiración en Pinterest.	1	1	1	1	1	0,2	0,6	7
Act_6_RRSS_InteracPas_PT_074	RRSS	Interacción Pasiva	Pinterest	Navegar por Tableros de Inspiración	Viaje temático: Navegando por tableros en Pinterest.	1	1	1	1	1	0,2	0,6	7
Act_6_RRSS_InteracPas_FB_M_075	RRSS	Interacción Pasiva	Facebook Messenger	Iniciar sesión o registrarse fácilmente con tu cuenta de Facebook.	Comunicación directa: Iniciando sesión en Facebook Messenger.	1	1	1	1	1	0,8	0,6	1
Act_6_RRSS_InteracPas_FB_M_076	RRSS	Interacción Pasiva	Facebook Messenger	Lectura de Conversaciones y Medios Compartidos	Conversaciones fluidas: Leyendo mensajes y medios compartidos en Messenger.	1	1	1	1	1	0,8	0,6	1
Act_6_RRSS_InteracPas_FB_M_077	RRSS	Interacción Pasiva	Facebook Messenger	Leer Mensajes Antiguos y Recordar Conversaciones	¡Recuerdos digitales! Leyendo mensajes antiguos en Messenger.	1	1	1	1	1	0,8	0,6	1
Act_6_RRSS_InteracPas_LI_078	RRSS	Interacción Pasiva	LinkedIn	Iniciar sesión o registrarse	Conexiones profesionales: Iniciando sesión en LinkedIn.	1	1	1	1	1	1	0,6	0,8
Act_6_RRSS_InteracPas_LI_079	RRSS	Interacción Pasiva	LinkedIn	Exploración de Contenido Profesional	Carrera digital: Explorando contenido profesional en LinkedIn.	1	1	1	1	1	1	0,6	0,8
Act_6_RRSS_InteracPas_LI_080	RRSS	Interacción Pasiva	LinkedIn	Navegar por Publicaciones y Artículos en el Feed	Actualizaciones de carrera: Navegando por publicaciones en LinkedIn.	1	1	1	1	1	1	0,6	0,8
Act_6_RRSS_Config_GL_081	RRSS	Configuración	General	¿Qué es la configuración?	Control total: Descubriendo qué es la configuración.	1	1	1	1	1	1	0,5	1
Act_6_RRSS_Config_GL_082	RRSS	Configuración	General	¿Para qué configuramos?	A tu medida: Explorando por qué configuramos.	1	1	1	1	1	1	0,5	1
Act_6_RRSS_Config_FB_083	RRSS	Configuración	Facebook	Ajustar notificaciones y personalizar preferencias de contenido en el Feed.	¡A tu manera! Personalizando notificaciones y preferencias en Facebook.	1	1	1	1	1	1	0,5	1
Act_6_RRSS_Config_YT_084	RRSS	Configuración	Youtube	Personalizar configuraciones de reproducción automática y notificaciones de canales suscritos.	Videos a medida: Personalizando configuraciones en Youtube.	1	1	1	1	1	0,7	0,5	1
Act_6_RRSS_Config_WA_085	RRSS	Configuración	Whatsapp	Personalizar tonos de notificación y ajustar preferencias de privacidad de última vez.	¡Privacidad y personalización! Configurando Whatsapp.	1	1	1	1	1	1	0,5	1
Act_6_RRSS_Config_IG_086	RRSS	Configuración	Instagram	Configurar notificaciones de actividad y personalizar preferencias de exploración de contenido.	Estilo propio: Configurando notificaciones y preferencias en Instagram.	1	1	1	1	1	0,6	0,5	1
Act_6_RRSS_Config_TT_087	RRSS	Configuración	TikTok	Ajustar preferencias de notificación de nuevos seguidores y configuración de reproducción automática.	¡Ajustes divertidos! Personalizando notificaciones en TikTok.	1	1	1	1	1	0,8	0,5	1
Act_6_RRSS_Config_TW_088	RRSS	Configuración	X (Twitter)	Configurar notificaciones de retweets y menciones, y personalizar preferencias de la línea de tiempo.	Tweets a medida: Configurando notificaciones en Twitter.	1	1	1	1	1	0,4	0,5	0,5
Act_6_RRSS_Config_PT_089	RRSS	Configuración	Pinterest	Configurar notificaciones en tableros y ajustar preferencias de descubrimiento de pines.	Inspiración a tu manera: Configurando notificaciones en Pinterest.	1	1	1	1	1	0,2	0,5	7
Act_6_RRSS_Config_FB_M_090	RRSS	Configuración	Facebook Messenger	Personalizar notificaciones de mensajes nuevos y ajustar preferencias de sonido y vibración.	Comunicación personalizada: Configurando notificaciones en Messenger.	1	1	1	1	1	0,8	0,5	1
Act_6_RRSS_Config_LI_091	RRSS	Configuración	LinkedIn	Configurar notificaciones de conexiones y mensajes directos, y personalizar preferencias de red.	Red profesional: Configurando notificaciones en LinkedIn.	1	1	1	1	1	1	0,5	0,8
Act_6_RRSS_InteracBas_FB_092	RRSS	Interaccion Básica	Facebook	Comentar en Publicaciones	¡Comparte tu opinión! Comentando en publicaciones de Facebook.	1	1	1	1	1	1	0,4	1
Act_6_RRSS_InteracBas_FB_093	RRSS	Interaccion Básica	Facebook	Enviar Mensajes Privados	¡Conéctate más! Enviando mensajes privados en Facebook.	1	1	1	1	1	1	0,4	1
Act_6_RRSS_InteracBas_FB_094	RRSS	Interaccion Básica	Facebook	Agregar Amigos	¡Haz nuevos lazos! Agregando amigos en Facebook.	1	1	1	1	1	1	0,4	1
Act_6_RRSS_InteracBas_YT_095	RRSS	Interaccion Básica	Youtube	Comentar en Videos	¡Opina sobre videos! Comentando en videos de Youtube.	1	1	1	1	1	0,7	0,4	1
Act_6_RRSS_InteracBas_YT_096	RRSS	Interaccion Básica	Youtube	Enviar Comentarios a Canales y Videos	¡Conecta con creadores! Enviando comentarios en Youtube.	1	1	1	1	1	0,7	0,4	1
Act_6_RRSS_InteracBas_YT_097	RRSS	Interaccion Básica	Youtube	Suscribirse a Canales	¡Sigue tu pasión! Suscribiéndote a canales en Youtube.	1	1	1	1	1	0,7	0,4	1
Act_6_RRSS_InteracBas_WA_098	RRSS	Interaccion Básica	Whatsapp	Comentar en Estados	¡Comparte tu día! Comentando estados en Whatsapp.	1	1	1	1	1	1	0,4	1
Act_6_RRSS_InteracBas_WA_099	RRSS	Interaccion Básica	Whatsapp	Enviar y Responder a Mensajes	¡Conversación fluida! Enviando y respondiendo mensajes en Whatsapp.	1	1	1	1	1	1	0,4	1
Act_6_RRSS_InteracBas_WA_100	RRSS	Interaccion Básica	Whatsapp	Agregar Nuevos Contactos	¡Expandiendo contactos! Agregando nuevos amigos en Whatsapp.	1	1	1	1	1	1	0,4	1
Act_6_RRSS_InteracBas_IG_101	RRSS	Interaccion Básica	Instagram	Comentar en Fotos y Videos	¡Expresa tu admiración! Comentando en fotos y videos de Instagram.	1	1	1	1	1	0,6	0,4	1
Act_6_RRSS_InteracBas_IG_102	RRSS	Interaccion Básica	Instagram	Enviar Mensajes Directos	¡Conexiones personales! Enviando mensajes directos en Instagram.	1	1	1	1	1	0,6	0,4	1
Act_6_RRSS_InteracBas_IG_103	RRSS	Interaccion Básica	Instagram	Seguir Nuevos Perfiles	¡Descubre nuevos horizontes! Siguiendo nuevos perfiles en Instagram.	1	1	1	1	1	0,6	0,4	1
Act_6_RRSS_InteracBas_TT_104	RRSS	Interaccion Básica	TikTok	Comentar en Videos Cortos	¡Diviértete y comenta! Comentando en videos cortos de TikTok.	1	1	1	1	1	0,8	0,4	1
Act_6_RRSS_InteracBas_TT_105	RRSS	Interaccion Básica	TikTok	Enviar Mensajes a Otros Usuarios	¡Conecta con creatividad! Enviando mensajes en TikTok.	1	1	1	1	1	0,8	0,4	1
Act_6_RRSS_InteracBas_TT_106	RRSS	Interaccion Básica	TikTok	Seguir a Creadores de Contenido	¡Sigue la magia! Siguiendo a creadores de contenido en TikTok.	1	1	1	1	1	0,8	0,4	1
Act_6_RRSS_InteracBas_TW_107	RRSS	Interaccion Básica	X (Twitter)	Comentar en Tweets	¡Participa en la conversación! Comentando en tweets de Twitter.	1	1	1	1	1	0,4	0,4	0,5
Act_6_RRSS_InteracBas_TW_108	RRSS	Interaccion Básica	X (Twitter)	Enviar Mensajes Directos	¡Comunícate directamente! Enviando mensajes directos en Twitter.	1	1	1	1	1	0,4	0,4	0,5
Act_6_RRSS_InteracBas_TW_109	RRSS	Interaccion Básica	X (Twitter)	Seguir Nuevos Usuarios	¡Expande tu red! Siguiendo a nuevos usuarios en Twitter.	1	1	1	1	1	0,4	0,4	0,5
Act_6_RRSS_InteracBas_PT_110	RRSS	Interaccion Básica	Pinterest	Comentar en Pines	¡Expresa tu inspiración! Comentando en pines de Pinterest.	1	1	1	1	1	0,2	0,4	7
Act_6_RRSS_InteracBas_PT_111	RRSS	Interaccion Básica	Pinterest	Enviar Mensajes a Otros Usuarios	¡Conecta a través de ideas! Enviando mensajes en Pinterest.	1	1	1	1	1	0,2	0,4	7
Act_6_RRSS_InteracBas_PT_112	RRSS	Interaccion Básica	Pinterest	Seguir Nuevos Tableros y Usuarios	¡Descubre nuevos mundos! Siguiendo nuevos tableros y usuarios en Pinterest.	1	1	1	1	1	0,2	0,4	7
Act_6_RRSS_InteracBas_FB_M_113	RRSS	Interaccion Básica	Facebook Messenger	Comentar en Conversaciones	¡Comparte tu experiencia! Comentando en conversaciones de Messenger.	1	1	1	1	1	0,8	0,4	1
Act_6_RRSS_InteracBas_FB_M_114	RRSS	Interaccion Básica	Facebook Messenger	Enviar Mensajes a Amigos y Grupos	¡Comunicación directa! Enviando mensajes a amigos y grupos en Messenger.	1	1	1	1	1	0,8	0,4	1
Act_6_RRSS_InteracBas_FB_M_115	RRSS	Interaccion Básica	Facebook Messenger	Agregar Nuevos Contactos	¡Amplía tu círculo! Agregando nuevos contactos en Messenger.	1	1	1	1	1	0,8	0,4	1
Act_6_RRSS_InteracBas_LI_116	RRSS	Interaccion Básica	LinkedIn	Comentar en Publicaciones y Artículos	¡Participa en lo profesional! Comentando en publicaciones y artículos de LinkedIn.	1	1	1	1	1	1	0,4	0,8
Act_6_RRSS_InteracBas_LI_117	RRSS	Interaccion Básica	LinkedIn	Enviar Mensajes a Conexiones y Profesionales	¡Conéctate profesionalmente! Enviando mensajes en LinkedIn.	1	1	1	1	1	1	0,4	0,8
Act_6_RRSS_InteracBas_LI_118	RRSS	Interaccion Básica	LinkedIn	Conectar con Nuevos Profesionales	¡Expande tu red laboral! Conectando con nuevos profesionales en LinkedIn.	1	1	1	1	1	1	0,4	0,8
Act_6_RRSS_InteracMed_FB_119	RRSS	Interaccion intermedia	Facebook	Publicar Estado con Texto e Imágenes	¡Comparte tu día! Publicando estados con texto e imágenes en Facebook.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_InteracMed_FB_120	RRSS	Interaccion intermedia	Facebook	Compartir Álbumes de Fotos y Videos	¡Recuerdos digitales! Compartiendo álbumes de fotos y videos en Facebook.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_InteracMed_FB_121	RRSS	Interaccion intermedia	Facebook	Utilizar la Cámara para Crear Historias	¡Historias visuales! Utilizando la cámara para crear historias en Facebook.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_InteracMed_YT_122	RRSS	Interaccion intermedia	Youtube	Subir Videos a la Plataforma	¡Crea y comparte! Subiendo videos a la plataforma de Youtube.	1	1	1	1	1	0,7	0,3	1
Act_6_RRSS_InteracMed_YT_123	RRSS	Interaccion intermedia	Youtube	Crear y Compartir Listas de Reproducción	¡Playlist personalizada! Creando y compartiendo listas de reproducción en Youtube.	1	1	1	1	1	0,7	0,3	1
Act_6_RRSS_InteracMed_YT_124	RRSS	Interaccion intermedia	Youtube	Utilizar la Cámara para Crear Contenido Multimedia	¡Cámara en acción! Utilizando la cámara para crear contenido multimedia en Youtube.	1	1	1	1	1	0,7	0,3	1
Act_6_RRSS_InteracMed_WA_125	RRSS	Interaccion intermedia	Whatsapp	Publicar Estados con Texto, Fotos y Videos	¡Exprésate en Whatsapp! Publicando estados con texto, fotos y videos.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_InteracMed_WA_126	RRSS	Interaccion intermedia	Whatsapp	Compartir Contenido Multimedia en Chats	¡Conexión multimedia! Compartiendo contenido multimedia en chats de Whatsapp.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_InteracMed_WA_127	RRSS	Interaccion intermedia	Whatsapp	Tomar y Compartir Fotos y Videos desde la Aplicación	¡Captura y comparte! Tomando y compartiendo fotos y videos desde la aplicación de Whatsapp.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_InteracMed_IG_128	RRSS	Interaccion intermedia	Instagram	Publicar Fotos y Videos en el Feed	¡Tu galería digital! Publicando fotos y videos en el feed de Instagram.	1	1	1	1	1	0,6	0,3	1
Act_6_RRSS_InteracMed_IG_129	RRSS	Interaccion intermedia	Instagram	Compartir Historias con Contenido Efímero	¡Historias que desaparecen! Compartiendo historias con contenido efímero en Instagram.	1	1	1	1	1	0,6	0,3	1
Act_6_RRSS_InteracMed_IG_130	RRSS	Interaccion intermedia	Instagram	Utilizar la Cámara para Crear Contenido Visual	¡Crea visualmente! Utilizando la cámara para crear contenido visual en Instagram.	1	1	1	1	1	0,6	0,3	1
Act_6_RRSS_InteracMed_TT_131	RRSS	Interaccion intermedia	TikTok	Crear y Publicar Videos Cortos	¡Diviértete creando! Creando y publicando videos cortos en TikTok.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_InteracMed_TT_132	RRSS	Interaccion intermedia	TikTok	Utilizar la Cámara para Grabar Contenido Divertido	¡Diversión en cada grabación! Utilizando la cámara para grabar contenido divertido en TikTok.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_InteracMed_TT_133	RRSS	Interaccion intermedia	TikTok	Compartir Videos con Efectos y Ediciones	¡Añade magia a tus videos! Compartiendo videos con efectos y ediciones en TikTok.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_InteracMed_TW_134	RRSS	Interaccion intermedia	X (Twitter)	Twittear con Texto y Multimedia	¡Exprésate en 280 caracteres! Twitteando con texto y multimedia en Twitter.	1	1	1	1	1	0,4	0,3	0,5
Act_6_RRSS_InteracMed_TW_135	RRSS	Interaccion intermedia	X (Twitter)	Compartir Fotos y Videos en Tweets	¡Visualiza tu mundo! Compartiendo fotos y videos en tweets de Twitter.	1	1	1	1	1	0,4	0,3	0,5
Act_6_RRSS_InteracMed_TW_136	RRSS	Interaccion intermedia	X (Twitter)	Utilizar la Cámara para Capturar Momentos	¡Captura momentos únicos! Utilizando la cámara para capturar momentos en Twitter.	1	1	1	1	1	0,4	0,3	0,5
Act_6_RRSS_InteracMed_PT_137	RRSS	Interaccion intermedia	Pinterest	Pinear y Compartir Imágenes Inspiradoras	¡Inspira y comparte! Pineando y compartiendo imágenes inspiradoras en Pinterest.	1	1	1	1	1	0,2	0,3	7
Act_6_RRSS_InteracMed_PT_138	RRSS	Interaccion intermedia	Pinterest	Crear Tableros Temáticos y Publicar Contenido	¡Organiza tu inspiración! Creando tableros temáticos y publicando contenido en Pinterest.	1	1	1	1	1	0,2	0,3	7
Act_6_RRSS_InteracMed_PT_139	RRSS	Interaccion intermedia	Pinterest	Utilizar la Cámara para Capturar Ideas Visuales	¡Captura tu creatividad! Utilizando la cámara para capturar ideas visuales en Pinterest.	1	1	1	1	1	0,2	0,3	7
Act_6_RRSS_InteracMed_FB_M_140	RRSS	Interaccion intermedia	Facebook Messenger	Compartir Fotos y Videos en Conversaciones	¡Conexión multimedia! Compartiendo fotos y videos en conversaciones de Messenger.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_InteracMed_FB_M_141	RRSS	Interaccion intermedia	Facebook Messenger	Publicar Actualizaciones de Estado	¡Actualízate en Messenger! Publicando actualizaciones de estado en Messenger.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_InteracMed_FB_M_142	RRSS	Interaccion intermedia	Facebook Messenger	Utilizar la Cámara para Enviar Fotos y Videos	¡Envía momentos visuales! Utilizando la cámara para enviar fotos y videos en Messenger.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_InteracMed_LI_143	RRSS	Interaccion intermedia	LinkedIn	Publicar Actualizaciones de Estado y Contenido Profesional	¡Profesional y actualizado! Publicando actualizaciones de estado y contenido en LinkedIn.	1	1	1	1	1	1	0,3	0,8
Act_6_RRSS_InteracMed_LI_144	RRSS	Interaccion intermedia	LinkedIn	Compartir Artículos y Publicaciones	¡Comparte tu conocimiento! Compartiendo artículos y publicaciones en LinkedIn.	1	1	1	1	1	1	0,3	0,8
Act_6_RRSS_InteracMed_LI_145	RRSS	Interaccion intermedia	LinkedIn	Utilizar la Cámara para Crear Contenido de Carrera	¡Visualiza tu trayectoria! Utilizando la cámara para crear contenido de carrera en LinkedIn.	1	1	1	1	1	1	0,3	0,8
Act_6_RRSS_SegPriv_FB_146	RRSS	Seguridad y privacidad	Facebook	Revisar y Ajustar Configuración de Privacidad en "Configuración"	¡Tu espacio seguro! Revisando y ajustando la configuración de privacidad en Facebook.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_SegPriv_FB_147	RRSS	Seguridad y privacidad	Facebook	No Compartir Información Personal Sensible en el Perfil	¡Protege tu identidad! Evitando compartir información personal sensible en el perfil de Facebook.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_SegPriv_FB_148	RRSS	Seguridad y privacidad	Facebook	Ignorar Solicitudes de Amistad de Desconocidos	¡Círculo confiable! Ignorando solicitudes de amistad de desconocidos en Facebook.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_SegPriv_YT_149	RRSS	Seguridad y privacidad	Youtube	Configurar Privacidad del Canal en "Configuración de Privacidad"	¡Tu canal, tus reglas! Configurando la privacidad del canal en Youtube.	1	1	1	1	1	0,7	0,3	1
Act_6_RRSS_SegPriv_YT_150	RRSS	Seguridad y privacidad	Youtube	Ser Cauteloso al Compartir Comentarios o Información Personal	¡Comenta con cuidado! Siendo cauteloso al compartir comentarios o información personal en Youtube.	1	1	1	1	1	0,7	0,3	1
Act_6_RRSS_SegPriv_YT_151	RRSS	Seguridad y privacidad	Youtube	Desactivar Comentarios en Videos si se Prefiere	¡Controla tu espacio! Desactivando comentarios en videos si así lo prefieres en Youtube.	1	1	1	1	1	0,7	0,3	1
Act_6_RRSS_SegPriv_WA_152	RRSS	Seguridad y privacidad	Whatsapp	Configurar Opciones de Privacidad en "Cuenta"	¡Tu privacidad, tus reglas! Configurando opciones de privacidad en Whatsapp.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_SegPriv_WA_153	RRSS	Seguridad y privacidad	Whatsapp	No Abrir Enlaces o Descargar Archivos de Desconocidos	¡Cuida tu seguridad! Evitando abrir enlaces o descargar archivos de desconocidos en Whatsapp.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_SegPriv_WA_154	RRSS	Seguridad y privacidad	Whatsapp	Evitar Compartir Información Financiera o Personal por Mensajes	¡Protege tus datos! Evitando compartir información financiera o personal por mensajes en Whatsapp.	1	1	1	1	1	1	0,3	1
Act_6_RRSS_SegPriv_IG_155	RRSS	Seguridad y privacidad	Instagram	Ajustar Configuración de Privacidad en "Configuración de Cuenta"	¡Contenido controlado! Ajustando la configuración de privacidad en Instagram.	1	1	1	1	1	0,6	0,3	1
Act_6_RRSS_SegPriv_IG_156	RRSS	Seguridad y privacidad	Instagram	Revisar y Eliminar Seguidores No Deseados	¡Círculo confiable! Revisando y eliminando seguidores no deseados en Instagram.	1	1	1	1	1	0,6	0,3	1
Act_6_RRSS_SegPriv_IG_157	RRSS	Seguridad y privacidad	Instagram	Utilizar Contraseña Fuerte para Proteger la Cuenta	¡Cuenta segura! Utilizando una contraseña fuerte para proteger la cuenta en Instagram.	1	1	1	1	1	0,6	0,3	1
Act_6_RRSS_SegPriv_TT_158	RRSS	Seguridad y privacidad	TikTok	Configurar la Privacidad de la Cuenta en "Configuración de Privacidad"	¡Tu espacio, tus reglas! Configurando la privacidad de la cuenta en TikTok.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_SegPriv_TT_159	RRSS	Seguridad y privacidad	TikTok	Ser Cauteloso al Compartir Detalles Personales en Videos	¡Cautela creativa! Siendo cuidadoso al compartir detalles personales en videos de TikTok.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_SegPriv_TT_160	RRSS	Seguridad y privacidad	TikTok	Revisar y Eliminar Comentarios No Deseados en Publicaciones	¡Comentarios seguros! Revisando y eliminando comentarios no deseados en publicaciones de TikTok.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_SegPriv_TW_161	RRSS	Seguridad y privacidad	X (Twitter)	Ajustar Configuración de Privacidad en "Configuración y Privacidad"	¡Tu espacio, tus reglas! Ajustando la configuración de privacidad en Twitter.	1	1	1	1	1	0,4	0,3	0,5
Act_6_RRSS_SegPriv_TW_162	RRSS	Seguridad y privacidad	X (Twitter)	Evitar Compartir Información de Ubicación en Tweets	¡Protege tu ubicación! Evitando compartir información de ubicación en tweets de Twitter.	1	1	1	1	1	0,4	0,3	0,5
Act_6_RRSS_SegPriv_TW_163	RRSS	Seguridad y privacidad	X (Twitter)	No Hacer Clic en Enlaces de Origen Desconocido	¡Navega seguro! Evitando hacer clic en enlaces de origen desconocido en Twitter.	1	1	1	1	1	0,4	0,3	0,5
Act_6_RRSS_SegPriv_PT_164	RRSS	Seguridad y privacidad	Pinterest	Revisar Configuración de Privacidad en "Configuración de Cuenta"	¡Inspira con seguridad! Revisando la configuración de privacidad en Pinterest.	1	1	1	1	1	0,2	0,3	7
Act_6_RRSS_SegPriv_PT_165	RRSS	Seguridad y privacidad	Pinterest	Mantener Tableros Privados para Contenido Sensible	¡Privacidad creativa! Manteniendo tableros privados para contenido sensible en Pinterest.	1	1	1	1	1	0,2	0,3	7
Act_6_RRSS_SegPriv_PT_166	RRSS	Seguridad y privacidad	Pinterest	Ser Cauteloso al Pinear Contenido con Enlaces Externos	¡Cautela visual! Siendo cauteloso al pinear contenido con enlaces externos en Pinterest.	1	1	1	1	1	0,2	0,3	7
Act_6_RRSS_SegPriv_FB_M_167	RRSS	Seguridad y privacidad	Facebook Messenger	Utilizar Opciones de Bloqueo y Reporte para Contactos Indeseados	¡Contactos bajo control! Utilizando opciones de bloqueo y reporte en Facebook Messenger.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_SegPriv_FB_M_168	RRSS	Seguridad y privacidad	Facebook Messenger	Evitar Compartir Detalles Personales o Financieros por Mensajes	¡Protege tu información! Evitando compartir detalles personales o financieros por mensajes en Facebook Messenger.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_SegPriv_FB_M_169	RRSS	Seguridad y privacidad	Facebook Messenger	No Abrir Enlaces de Desconocidos en Conversaciones	¡Conversaciones seguras! No abriendo enlaces de desconocidos en conversaciones de Messenger.	1	1	1	1	1	0,8	0,3	1
Act_6_RRSS_SegPriv_LI_170	RRSS	Seguridad y privacidad	LinkedIn	Revisar Configuración de Privacidad en "Configuración y Privacidad"	¡Profesional y seguro! Revisando la configuración de privacidad en LinkedIn.	1	1	1	1	1	1	0,3	0,8
Act_6_RRSS_SegPriv_LI_171	RRSS	Seguridad y privacidad	LinkedIn	Conectar Solo con Personas Conocidas y Confiables	¡Conexiones confiables! Conectando solo con personas conocidas y confiables en LinkedIn.	1	1	1	1	1	1	0,3	0,8
Act_6_RRSS_SegPriv_LI_172	RRSS	Seguridad y privacidad	LinkedIn	No Compartir Información Sensible en la Descripción del Perfil	¡Perfil profesional seguro! No compartiendo información sensible en la descripción del perfil en LinkedIn.	1	1	1	1	1	1	0,3	0,8
 */
